version: "3"

services:
  simplify-nerf:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
      - "3001:3001"
      - "4173:4173"
      - "7007:7007"
    volumes:
      - data:/workspace

volumes:
  data:
